version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=urlshrter
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - db: /var/lib/postgresql/data
    

  cache:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
    command: redis-server 
    volumes: 
      - cache:/data


volumes:
  cache:
    driver: local