# Generated by Django 5.1.1 on 2024-09-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_url_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
